# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Desing Portofolio
email: eltocayo.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specialising in Jekyll, 
  HYML, CSS and Javascript
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eltocayo.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: /:categories/:title


# Build settings
markdown: kramdown
